### ISSUE TITLE
It seems difficult to process white region.

### ISSUE THREAD

**Issue by Dugudaibo** [MarcioCerqueira/RealTimeSpecularHighlightRemoval#1]
Thank you very much for your paper and code. It can process well on the images which are showed in your paper. However, I use it to process my images which has much white region, such as white wall, white desk, white car and so on. It always turn white into black or color like black. I try to change the parameters but nothing. Could you give me some advice?

**Comment by MarcioCerqueira** [comment]
Hi @Dugudaibo,

As I have shown [in Fig. 7 of the supplementary material of this work,](https://marciocerqueira.github.io/docs/2018/conferences/SIBGRAPI-Main-Appendix.pdf)  most of the techniques proposed in the field of specular highlight removal (including ours) are not able to effectively remove specular highlights in the presence of large white regions. Indeed, that is **still** a limitation of our work.

**Comment by Dugudaibo** [comment]
It is so kind of you. Thank you for reply so quickly!
However, it is so sad that I must find a new method to remove specular highlights in the presence of large white regions.

**Comment by xl0714** [comment]
how  to run?
