### ISSUE TITLE
Corrupted output

### ISSUE THREAD

**Issue by SubhiH** [MarcioCerqueira/RealTimeSpecularHighlightRemoval#2]
Thank you for sharing your great work!
I am trying to run it but the output seems to be corrupted as shown in the attached screenshot. Do you have any recommendation?
Thanks!

![rm](https://user-images.githubusercontent.com/2580270/52490490-d6c58800-2b92-11e9-9f1c-c05f631070be.PNG)

**Comment by MarcioCerqueira** [comment]
Hi!

Unfortunately, the current version of the algorithm only works for scenarios where a small (white) specular highlight is present, like the ones shown in the [original paper](https://marciocerqueira.github.io/docs/2018/conferences/SIBGRAPI-Main-Paper.pdf).

In a future release, we will try to address such a problem and increase the robustness of the algorithm.

Best Regards,
Márcio Macedo.

**Comment by SubhiH** [comment]
Thank you!
