### ISSUE TITLE
Update ReadMe.txt

### ISSUE THREAD

**Issue by vitorsr** [MarcioCerqueira/RealTimeSpecularHighlightRemoval#4]
Hi Márcio,

SIBGRAPI proceedings have been published. Could you add the full citation to the `ReadMe.txt` so people can find and cite your work easier?
> A. Carlos dos Santos Souza, M. Cerqueira de Farias Macedo, V. Paixao do Nascimento, and B. Santos Oliveira, “Real-Time High-Quality Specular Highlight Removal Using Efficient Pixel Clustering,” in 2018 31st SIBGRAPI Conference on Graphics, Patterns and Images (SIBGRAPI), 2018 [Online]. Available: http://dx.doi.org/10.1109/SIBGRAPI.2018.00014

Also here it is in IEEE Xplore.
> https://ieeexplore.ieee.org/document/8614311

**Comment by MarcioCerqueira** [comment]
Hi Vítor,

I have updated the ReadMe file taking into account your suggestion.

Thank you very much!

Best regards,
Márcio Macedo.
